FinancialManagement/urls.py
from django.urls import path

from FinancialManagement.views import CreditCardView

urlpatterns = [
    path('credit-card/', CreditCardView.as_view(), name='credit-card-view'),
]

apis/urls.py
from django.conf.urls import url
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from apis import views

urlpatterns = [
    url(r'^sign-up/$', views.SignUpAPIView.as_view(), name="api-sign-up"),
    url(r'^sign-in/$', views.SignInAPIView.as_view(), name="api-sign-in"),
    url(r'^show-profile/', views.ProfileAPIView.as_view(), name='api-profile'),
    url(r'^edit-profile/', views.EditProfileAPIView.as_view(), name='api-edit-profile'),
    url(r'^add-book/', views.AddBookAPIView.as_view(), name='api-add-book'),
    url(r'^show-books/', views.ShowAllBooksAPIView.as_view(), name='api-show-books'),
    url(r'^show-book-info/', views.ShowBookInfoAPIView.as_view(), name='api-show-book-info'),
    url(r'^show-mybooks/', views.ShowMyBooksAPIView.as_view(), name='api-show-mybooks'),
    url(r'^show-my-rented-books/', views.ShowMyRentedBooksAPIView.as_view(), name='api-show-my-rented-books'),
    url(r'^borrow-book/', views.RentBookAPIView.as_view(), name='rent-book'),
    url(r'^show-invitation-code/', views.ShowInvitationCodeAPIView.as_view(), name='api-show-invitation-code'),
    url(r'^show-charge/', views.ShowChargeAPIView.as_view(), name='api-show-charge'),
    url(r'^raise-charge/', views.RaiseChargeAPIView.as_view(), name='api-raise-charge'),


    # add the following URL route to enable obtaining a token via a POST included the user's username and password.
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),
]


urlpatterns = format_suffix_patterns(urlpatterns)

ketabyar/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.views.static import serve

from ketabyar import settings
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('accounts/', include('accounts.urls')),
    path('accounting/', include('FinancialManagement.urls')),
    path('book/', include('books.urls', namespace='book')),
    path('apis/', include('apis.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),  # TODO yadam nemiad ino vase chi gozashtam :))
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
]

FinancialManagement/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from accounts.models import Member


class CreditCard(models.Model):
    assosiated_user = models.ForeignKey(Member, related_name='credit_card', on_delete=models.CASCADE, null=True)
    asset = models.IntegerField(default=0)

    def __str__(self):
        return str(self.asset)+" "+str(self.assosiated_user)

    def increase_credit(self, amount):
        self.asset += int(amount)
        self.save()
        return self.asset

    def decrease_credit(self, amount):
        self.asset -= int(amount)
        self.save()
        return self.asset



# this is signal,should be moved to proper file :))
@receiver(post_save, sender=Member)
def create_credit_card(sender, instance, **kwargs):
    if kwargs['created']:
        CreditCard.objects.create(assosiated_user=instance, asset=0)

FinancialManagement/forms.py
from django import forms

from FinancialManagement.models import CreditCard


class CreditCardForm(forms.Form):

    class Meta:
        model = CreditCard
        fields = 'asset'

FinancialManagement/views.py
import random

from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import FormView

from FinancialManagement.forms import CreditCardForm
from FinancialManagement.models import CreditCard


class CreditCardView(FormView):
    template_name = 'credit-card-view.html'
    form_class = CreditCardForm
    success_url = '/accounting/credit-card/'

    def get_context_data(self, **kwargs):
        context = super(CreditCardView, self).get_context_data(**kwargs)
        try:
            context['balance'] = CreditCard.objects.get(assosiated_user=self.request.user)
        except ObjectDoesNotExist:
            return None
        return context

    def form_valid(self, form):
        asset = int(self.request.POST['asset'])
        card = CreditCard.objects.get(assosiated_user=self.request.user)
        card.increase_credit(asset)
        return super().form_valid(form)

FinancialManagement/templates/credit-card-increased.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    your amount increasing form
    <br>
    <br><br>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message" />
    </form>
</body>
</html>

FinancialManagement/templates/credit-card-view.html
{% extends 'profile_base.html' %}
{% load static %}
{% block profile_content %}
    <div class="col-lg-10" style="margin-right: 5%">
        <section class="panel">
            <div class="invitation-code-pan">اعتبار حساب:     {{ balance.asset }}</div>
            <div class="panel-body">
                <form class="form-horizontal tasi-form" href="{% url 'credit-card-view' %}" method="post">
                    <div class="form-group">
                        <label class="col-sm-1 control-label">مبلغ:</label>
                        <div class="col-sm-5">
                            <input id="id_asset" type="number" class="form-control" autofocus name="asset">
                            <span class="error-block">{{ form.asset.errors }}</span>
                        </div>
                        <button class="col-sm-2 btn btn-shadow btn-success" type="submit">افزایش اعتبار</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
{% endblock %}