apis/urls.py
from django.conf.urls import url
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from apis import views

urlpatterns = [
    url(r'^sign-up/$', views.SignUpAPIView.as_view(), name="api-sign-up"),
    url(r'^sign-in/$', views.SignInAPIView.as_view(), name="api-sign-in"),
    url(r'^show-profile/', views.ProfileAPIView.as_view(), name='api-profile'),
    url(r'^edit-profile/', views.EditProfileAPIView.as_view(), name='api-edit-profile'),
    url(r'^add-book/', views.AddBookAPIView.as_view(), name='api-add-book'),
    url(r'^show-books/', views.ShowAllBooksAPIView.as_view(), name='api-show-books'),
    url(r'^show-book-info/', views.ShowBookInfoAPIView.as_view(), name='api-show-book-info'),
    url(r'^show-mybooks/', views.ShowMyBooksAPIView.as_view(), name='api-show-mybooks'),
    url(r'^show-my-rented-books/', views.ShowMyRentedBooksAPIView.as_view(), name='api-show-my-rented-books'),
    url(r'^borrow-book/', views.RentBookAPIView.as_view(), name='rent-book'),
    url(r'^show-invitation-code/', views.ShowInvitationCodeAPIView.as_view(), name='api-show-invitation-code'),
    url(r'^show-charge/', views.ShowChargeAPIView.as_view(), name='api-show-charge'),
    url(r'^raise-charge/', views.RaiseChargeAPIView.as_view(), name='api-raise-charge'),


    # add the following URL route to enable obtaining a token via a POST included the user's username and password.
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),
]


urlpatterns = format_suffix_patterns(urlpatterns)

books/urls.py
from django.urls import path

from books.views import BookDetail, EditBook, BookList, AddNewBook, BorrowedBookListView, BorrowBookView, \
    ReturnBookView, MyBooksView, SearchView

app_name = 'book'

urlpatterns = [
    # ex: /5/
    path('<int:pk>/', BookDetail.as_view(), name='book-detail'),
    path('add/', AddNewBook.as_view(), name='book-add'),
    path('edit/<int:pk>/', EditBook.as_view(), name='book-edit'),
    path('list/', BookList.as_view(), name='book-list'),
    path('borrow/<int:pk>', BorrowBookView.as_view(), name='borrow-a-book'),
    path('return/<int:pk>', ReturnBookView.as_view(), name='return-a-book'),
    path('borrowed-list/', BorrowedBookListView.as_view(), name='borrowed-book-list'),
    path('my-books/', MyBooksView.as_view(), name='my-books'),
    path('search/', SearchView.as_view(), name='book-search'),
]

ketabyar/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.views.static import serve

from ketabyar import settings
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('accounts/', include('accounts.urls')),
    path('accounting/', include('FinancialManagement.urls')),
    path('book/', include('books.urls', namespace='book')),
    path('apis/', include('apis.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),  # TODO yadam nemiad ino vase chi gozashtam :))
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
]

books/models.py
import datetime
from django.db import models

from accounts.models import Member
from ketabyar.settings import AGE_RANGES, GENRES, SIZES
from utility.models import Image


class Book(models.Model):

    owner = models.ForeignKey(to=Member, related_name='books', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=30)
    age_range = models.CharField(choices=AGE_RANGES, max_length=10, blank=True)
    writer = models.CharField(max_length=30, null=True, blank=True)
    genre = models.CharField(choices=GENRES, max_length=50,null=True, blank=True)
    key_words = models.CharField(max_length=50, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    size = models.CharField(choices=SIZES, max_length=10, null=True, blank=True)
    volume_number = models.IntegerField(default=1)
    image = models.ImageField(upload_to='book_images', null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    summary = models.CharField(max_length=200, null=True, blank=True)
    weekly_price = models.IntegerField(default=1000)
    original_price = models.IntegerField(default=1000)
    is_borrowed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def mark_book_as_borrowed(self):
        self.is_borrowed = True
        self.save()
        return

    def mark_book_as_returned(self):
        self.is_borrowed = False
        self.save()
        return


class BorrowBook(models.Model):
    book = models.ForeignKey(to=Book, on_delete=models.CASCADE, related_name="amanat")
    borrower = models.ForeignKey(to=Member, on_delete=models.CASCADE, related_name="list_amanat_gerefte_shode")
    date = models.DateField(auto_now_add=True)
    deadline = models.DateField()
    number_of_extension = models.IntegerField(default=0)
    returned = models.BooleanField(default=False)

    def calculate_hazine(self):
        num_of_borrowed_week = (datetime.datetime.now().date() - self.date).days/7
        print(datetime.datetime.now().date())
        print(self.date)
        return self.book.weekly_price * num_of_borrowed_week

    def __str__(self):
        return str(self.book).upper()+" is given by "+str(self.book.owner).upper()+" to "+str(self.borrower).upper()

books/views.py
import datetime

from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView, CreateView, TemplateView, FormView

from books.models import Book, BorrowBook


class BookDetail(DetailView):
    model = Book
    template_name = 'book-info.html'


class EditBook(UpdateView):
    model = Book
    template_name = 'edit-book.html'
    fields = ('title', 'age_range', 'writer', 'genre', 'key_words', 'release_date',
              'size', 'volume_number', 'image', 'description', 'summary', 'summary',
              'weekly_price', 'original_price')

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse('book:book-detail', args=[pk])


class BookList(ListView):
    model = Book
    template_name = 'book-list.html'


class AddNewBook(CreateView):
    model = Book
    template_name = 'add-new-book.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse('book:book-list')


class BorrowBookView(CreateView):
    model = BorrowBook
    template_name = 'borrow-book.html'
    fields = ('deadline', 'book')

    def get_success_url(self):
        return reverse('book:borrowed-book-list')

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        book_pk = kwargs.get('pk')
        book = Book.objects.get(pk=book_pk)
        borrower = request.user
        if book.is_borrowed:
            return HttpResponse("Sorry the book was reserved before")
        if borrower.credit_card.all()[0].asset >= book.weekly_price:
            borrower.credit_card.all()[0].decrease_credit(book.weekly_price)
            book.owner.credit_card.all()[0].increase_credit(book.weekly_price)
        else:
            return HttpResponse("Sorry you should increase your balance")
        now = datetime.datetime.now()
        deadline = now + datetime.timedelta(days=14)
        book.mark_book_as_borrowed()
        BorrowBook.objects.create(book=book, borrower=borrower, deadline=deadline)
        return redirect(to=reverse('book:borrowed-book-list'))


class BorrowedBookListView(ListView):
    model = BorrowBook
    template_name = 'borrowed-book-list.html'


class ReturnBookView(UpdateView):
    model = Book
    fields = '__all__'

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs.get('pk')
        book = Book.objects.get(pk=pk)
        borrow_books = BorrowBook.objects.filter(book=book)
        last_borrowed_book = borrow_books.reverse()[0]
        if request.user != last_borrowed_book.borrower:
            return HttpResponse("you have not borrowed this book")
        last_borrowed_book.book.mark_book_as_returned()
        last_borrowed_book.returned = True
        last_borrowed_book.save()
        return redirect(to=reverse('book:borrowed-book-list'))


class MyBooksView(TemplateView):
    template_name = 'book-list.html'

    def get_context_data(self, **kwargs):
        object_list = Book.objects.filter(owner=self.request.user)
        context = {'object_list': object_list}
        return context


class SearchView(TemplateView):
    template_name = 'book-list.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('query')
        object_list = Book.objects.filter(title__icontains=query)
        context = {'object_list': object_list}
        return context

books/templates/add-new-book.html
{% extends 'profile_base.html' %}
{% block profile_content %}
        {% if message != None %}
            <div class="alert alert-success alert-block fade in">
                <button data-dismiss="alert" class="close close-sm" type="button">
                    <i class="icon-remove"></i>
                </button>
                <h4>
                    <i class="icon-ok-sign"></i>
                   کتاب با موفقیت ثبت شد.
                </h4>
                <p>{{ message }}</p>
            </div>
        {% endif %}
        <!-- page start-->
            <div class="col-lg-10" style="margin-right: 5%">
                <section class="panel">
                    <header class="panel-heading">
                    ثبت کتاب جدید
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal tasi-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% load widget_tweaks %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">عنوان*</label>
                                <div class="col-sm-10">
                                    {{ form.title |add_class:"form-control"}}
{#                                    <input id="id_username" type="text" class="form-control" autofocus name="username" value="{{ object.username }}">#}
                                    <span class="error-block">{{ form.title.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">رده سنی</label>
                                <div class="col-sm-10">
                                    {{ form.age_range |add_class:"form-control"}}
                                    <span class="error-block">{{ form.age_range.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">نویسنده</label>
                                <div class="col-sm-10">
                                    {{ form.writer |add_class:"form-control"}}
                                    <span class="error-block">{{ form.writer.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">سبک</label>
                                <div class="col-sm-10">
                                    {{ form.genre |add_class:"form-control"}}
                                    <span class="error-block">{{ form.genre.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">کلیدواژه ها</label>
                                <div class="col-sm-10">
                                    {{ form.key_words |add_class:"form-control"}}
                                    <span class="error-block">{{ form.key_words.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">تاریخ انتشار</label>
                                <div class="col-sm-10">
                                    <input id="id_release_date" type="date" class="form-control" autofocus name="release_date" value="{{ form.release_date.value|default_if_none:"" }}">
                                    <span class="error-block">{{ form.release_date.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">ابعاد</label>
                                <div class="col-sm-10">
                                    {{ form.size |add_class:"form-control"}}
                                    <span class="error-block">{{ form.size.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">تعداد صفحات</label>
                                <div class="col-sm-10">
                                    {{ form.volume_number |add_class:"form-control"}}
                                    <span class="error-block">{{ form.volume_number.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">تصویر</label>
                                <div class="col-sm-10">
                                    {{ form.image |add_class:"form-control"}}
                                    <span class="error-block">{{ form.image.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">توضیحات</label>
                                <div class="col-sm-10">
                                    {{ form.description |add_class:"form-control"}}
                                    <span class="error-block">{{ form.description.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">خلاصه</label>
                                <div class="col-sm-10">
                                    {{ form.summary |add_class:"form-control"}}
                                    <span class="error-block">{{ form.summary.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">هزینه امانت هفتگی</label>
                                <div class="col-sm-10">
                                    {{ form.weekly_price |add_class:"form-control"}}
                                    <span class="error-block">{{ form.weekly_price.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">ارزش کتاب</label>
                                <div class="col-sm-10">
                                    {{ form.original_price |add_class:"form-control"}}
                                    <span class="error-block">{{ form.original_price.errors }}</span>
                                </div>
                            </div>
                            <input type="hidden" id="id_owner" name="owner" value="{{ request.user.id }}"/>
                            <button class="btn btn-shadow btn-success" type="submit">ثبت</button>
                        </form>
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->

{% endblock %}

books/templates/book-info.html
{% extends 'profile_base.html' %}
{% load static %}
{% block profile_content %}
                <div class="row" style="margin-right: 20%">
                  <div class="col-md-8">
                    <div class="thumbnail">
                        {% if book.image %}
                            <img class="book-detail-image" src="{{ book.image.url }}" alt="{{ book.title }}">
                        {% else %}
                            <img class="book-detail-image" src="{% static 'img/default_book_pic.jpg' %}" alt="{{ book.title }}">
                        {% endif %}
                        <div class="caption" style="text-align: center">
                            <div class="book-detail">
                                <span class="book-detail-key">عنوان:</span><span>{{ book.title }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">رده سنی:</span><span>{{ book.get_age_range_display|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">نویسنده:</span><span>{{ book.writer|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">سبک:</span><span>{{ book.get_genre_display|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">کلیدواژه ها:</span><span>{{ book.key_words|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">تاریخ انتشار:</span><span>{{ book.release_date|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">ابعاد:</span><span>{{ book.get_size_display|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">تعداد صفحات:</span><span>{{ book.volume_number|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">توضیحات:</span><span>{{ book.description|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">خلاصه:</span><span>{{ book.summary|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">هزینه امانت هفتگی:</span><span>{{ book.weekly_price|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">ارزش کتاب:</span><span>{{ book.original_price|default_if_none:"" }}</span>
                            </div>
                            <div class="book-detail">
                                <span class="book-detail-key">وضعیت:</span><span>{% if book.is_borrowed %}امانت گرفته شده{% else %}موجود{% endif %}</span>
                            </div>
                          {% if book.owner.username == user.username  %}
                            <a class="btn btn-md btn-warning" href="{% url 'book:book-edit' pk=book.id %}">ویرایش</a>
                          {% elif not book.is_borrowed%}
                              {% for card in user.credit_card.all %}
                                  {% if card.asset < book.weekly_price %}
                                      <button class="btn btn-md btn-success" href="{% url 'registration_register' %}" disabled>درخواست امانت</button>
                                      <div style="color: darkred;font-weight: bold">اعتبار کافی نیست!</div>
                                  {% else %}
                                      <a class="btn btn-md btn-success" href="{% url 'book:borrow-a-book' pk=book.id %}">درخواست امانت</a>
                                  {% endif %}
                              {% endfor %}
                          {% endif %}
                        </div>
                    </div>
                  </div>
                </div>
{% endblock %}

books/templates/book-list.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<ul>#}
{#{% for book in object_list %}#}
{#    <li>{{ book.release_date|date }} - {{ book.title }}</li>#}
{#{% empty %}#}
{#    <li>No articles yet.</li>#}
{#{% endfor %}#}
{#</ul>#}
{#</body>#}
{#</html>#}
{% extends 'profile_base.html' %}
{% load static %}
{% block profile_content %}
    <div class="row">
        {% for book in object_list %}
            <a href="{% url 'book:book-detail' pk=book.id %}">
              <div class="col-md-3" style="margin-top: 10px">
                    <div class="thumbnail">
                        <div>
                            {% if book.image %}
                                <img class="book-list-image" src="{{ book.image.url }}" alt="{{ book.title }}">
                            {% else %}
                                <img class="book-list-image" src="{% static 'img/default_book_pic.jpg' %}" alt="{{ book.title }}">
                            {% endif %}
                        </div>
                        <div class="caption" style="text-align: center;">
                          <p style="color: black">{{ book.title }}</p><br>
                          <a class="btn btn-md btn-primary" href="{% url 'book:book-detail' pk=book.id %}">مشاهده</a>
                        </div>
                    </div>
              </div>
            </a>
        {% empty %}
        <p>No books yet.</p>
        {% endfor %}
    </div>
{% endblock %}

books/templates/borrow-book.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    sina
{% endblock %}

{{% block content %}
    {{ form.as_p }}
{% endblock %}

books/templates/borrowed-book-list.html
{#{% extends "base.html" %}#}
{#{% load static %}#}
{##}
{#{% block title %}#}
{#    sina#}
{#{% endblock %}#}
{##}
{#{{% block content %}#}
{#<ul>#}
{#{% for borrow_object in object_list %}#}
{#    <li>{{ borrow_object.book }} - {{ borrow_object.date|date }}</li>#}
{#{% empty %}#}
{#    <li>No Borrowed item yet.</li>#}
{#{% endfor %}#}
{#</ul>#}
{#{% endblock %}#}

{% extends 'profile_base.html' %}
{% load static %}
{% block profile_content %}
    <div class="row">
        {% for borrow_object in object_list %}
            {% if not borrow_object.returned and borrow_object.borrower == user %}
                <a href="{% url 'book:book-detail' pk=borrow_object.book.id %}">
                  <div class="col-md-3" style="margin-top: 10px">
                        <div class="thumbnail">
                            <div>
                                {% if borrow_object.book.image %}
                                    <img class="book-list-image" src="{{ borrow_object.book.image.url }}" alt="{{ borrow_object.book.title }}">
                                {% else %}
                                    <img class="book-list-image" src="{% static 'img/default_book_pic.jpg' %}" alt="{{ borrow_object.book.title }}">
                                {% endif %}
                            </div>
                            <div class="caption" style="text-align: center;">
                              <p style="color: black">{{ borrow_object.book.title }}</p>
                              <p style="color: black">{{ borrow_object.date | date }}</p>
                              <p style="color: black">{{ borrow_object.book.owner.get_full_name }}</p><br>
                              <a class="btn btn-md btn-primary" href="{% url 'book:book-detail' pk=borrow_object.book.id %}">مشاهده</a>
                              <a class="btn btn-md btn-danger" href="{% url 'book:return-a-book' pk=borrow_object.book.id %}">پس دادن</a>
                            </div>
                        </div>
                  </div>
                </a>
            {% endif %}
        {% empty %}
        <p>No books yet.</p>
        {% endfor %}
    </div>
{% endblock %}